// encoding: utf-8
= Active check mode

The core script can generate output as specified by link:https://www.monitoring-plugins.org/doc/guidelines.html#PLUGOUTPUT[monitoring plugins^].
In this case, manual installation and configuration is needed.

If someone wants to provide templates for some of the non-Checkmk monitoring system, feel free to do a pull request.

== Installation

By convention, active checks use the prefix `check_`, so installing it to `check_patchmon` probably makes most sense:

[source,console,subs="attributes+"]
----
root #  install -m \
    _omd_root/local/lib/python3/cmk_addons/plugins/patchmon/libexec/agent_patchmon \
    /usr/local/bin/check_patchmon
----

== Invocation

Running as active check requires passing the host name, which type of name (default is 'friendly_name') should be applied to identify the host and the parameter `--monitoring-plugin`.

Here, we specify caching of the host list for one hour (3600 seconds) and the patch and reboot information for 20 minutes (1200 seconds).
The host should be identified by it's `friendly_name`.

[source,console,subs="attributes+"]
----
monitoring $ check_patchmon --baseurl https://patchmon.mydomain.test \
    --name friendly_name \
    --check 1200 \
    --list 3600 \
    --secret  'patchmon_ae_decafbad:deadbeef' \
    --cache /tmp/agent_patchmon \
    --single-host somehostname \
    --monitoring-plugin \
    --reboot
security updates missing | security_updates=1;;;; total_updates=2;;;; duration=0.001s
monitoring $ echo $?
2
----

You can specify a pretty generic cache directory.
In the cache directory, a subdirectory with a name derived by the PatchMon user name will be created.
This means that all hosts sharing a secret will share the cache which keeps the REST-API calls for host lists fewer.
Additionally, it enables sharing a single cache file between checks for patches and checks for necessary reboots.

If you also want to check for necessary reboots, make sure to pass the flag `--reboot` also to the invocations to check for patches.

Checking for reboots requires the additional parameter `--only-reboot`:

[source,console,subs="attributes+"]
----
monitoring $ check_patchmon --baseurl https://patchmon.mydomain.test \
    --name friendly_name \
    --check 1200 \
    --list 3600 \
    --secret  'patchmon_ae_decafbad:deadbeef' \
    --cache /tmp/agent_patchmon \
    --single-host somehostname \
    --monitoring-plugin \
    --reboot --only-reboot
reboot required | duration=0.695s
Reason given: Reboot flag file exists (/var/run/reboot-required)  Running kernel: 6.8.0-136-generic, Installed kernel: 6.8.0-137-generic
monitoring $ echo $?
2
----

== Limitations

This is work in progress! Currently, error handling is subpar and features are missing:

* States are not yet configurable. Missing security updates always results in an exit code of 2. Only missing regular updates in 1. A required reboot also results in 2.

* Error handling for example for an unavailable host name or missing command line options is non-existent.

* Grace periods as available in the Checkmk check plug-in are not yet available.

I will add all of these over the next months.