#!/usr/bin/env python3
# Shebang needed this time to find the interpreter!

import requests
import argparse
import json
import time
import os
import re
import hashlib
import uuid
import random

from pathlib import Path

# Make sure this script can be run from Checkmk 2.3.0 onwards and as active check without Checkmk APIs
# The new password store API is available starting with 2.5.0
try:
    from cmk.password_store.v1_unstable import Secret, parser_add_secret_option, resolve_secret_option, dereference_secret
except ModuleNotFoundError:
    # Just use the old one if importing the new one fails...
    try:
        from cmk.utils import password_store as legacy_pw_store
    except ModuleNotFoundError:
        # Silently ignore
        True
    
# The new storage API is available starting with 2.5.0
try:
    from cmk.server_side_programs.v1_unstable import Storage
except ModuleNotFoundError:
    # Silently ignore
    True

def get_cli_arguments():
    parser = argparse.ArgumentParser("agent_patchmon")
    parser.add_argument(
        "--baseurl",
        help="Specify the baseurl for your PatchMon installation.",
    )
    parser.add_argument(
        "--name",
        help="Chose whether 'id', 'hostname' or 'friendly_name' should be used to create hostname. Default is 'friendly_name'.",
    )
    parser.add_argument(
        # Only makes sense when used as Checkmk special agent with piggyback mode 
        "--maxexec",
        help="State a maximum time the special agent should take to retrieve patch details. Default is 30s. Irrelevant when querying a single host.",
    )
    parser.add_argument(
        "--list",
        help='State the interval (in seconds) host lists should be cached before retrieving them. Default is 1800s, +/-10 percent are randomly applied to avoid conflicts from parallel calls.',
    )
    parser.add_argument(
        "--check",
        help='State the interval (in seconds) patch info for a single hosts should stay cached before retrieving. Default is 1800s, +/-10 percent are randomly applied to avoid conflicts from parallel calls.',
    )
    parser.add_argument(
        "--reboot",
        help="If present, also query whether a reboot is required and ask for the reasons.",
        action="store_true",
    )
    parser.add_argument(
        "--grace",
        help="Get the package list for being able to create a grace period in the check plugin.",
        action="store_true",
    )
    parser.add_argument(
        "--monitoring-plugin",
        help="Behave as monitoring plug-in for Nagios and related systems like Icinga.",
        action="store_true",
    ),
    parser.add_argument(
        "--only-reboot",
        help="Only check whether reboot is required. Only effective in monitoring plug-in mode.",
        action="store_true",
    ),
    parser.add_argument(
        "--single-host",
        help="Query only data for one host, this is necessary for using as monitoring-plugins.org compatible operation. If used in the special agent mode (Checkmk only), the output will not mapped in piggyback sections.",
    ),
    parser.add_argument(
        "--cache",
        help="Specify the directory to cache retrieved data.",
    ),
    parser.add_argument(
        "--states",
        help="Specify a comma separated list of the exit codes for: missing security updates, missing regular updates and a required reboot. The default is: 2,1,2.",
    ),
    try:
        # Try the 2.5.0 helper:
        parser_add_secret_option(
            parser,
            short="-s",
            long="--secret",
            help="Specify the id:token to log in to PatchMon.",
            required=True
        )
    except NameError:
        # Fall back to manually adding:
        parser.add_argument(
            "--secret-id",
            help="Reference the ID of the secret as stored in the password store. Requires being run from Checkmk 2.3.0 or higher.",
        )
        # Fall back to manually adding:
        parser.add_argument(
            "--secret",
            help="Specify the id:token to log in to PatchMon.",
        )
    return parser.parse_args()


def create_config(args):
    config = {
        'maxexec': 30,
        'listage': 1800,
        'hostage': 1800,
        'name': 'friendly_name',
        'states': [ 2, 1, 2 ],
        'secret': None,
        'secret_id': None,
        'baseurl': None,
        'cache': None,
        'single_host': None,
        'monitoring_plugin': False,
    }
    if args.monitoring_plugin:
        config['monitoring_plugin'] = True
    if args.maxexec:
        config['maxexec'] = int(args.maxexec)
    if args.list:
        config['listage'] = int(args.list)
    if args.check:
        config['hostage'] = int(args.check)
    if args.secret:
        config['secret'] = args.secret
    if args.secret_id:
        config['secret_id'] = args.secret_id
    if args.baseurl:
        config['baseurl'] = args.baseurl
    if args.cache:
        config['cache'] = args.cache
    if args.single_host:
        config['single_host'] = args.single_host
    if args.states:
        n = 0
        for s in args.states.split(','):
            config['states'][n] = int(s)
            n += 1
    for k in [ 'listage', 'hostage' ]:
        rnd = random.random()
        fac = 0.9 + rnd / 5.0
        config[k] = int(config[k] * fac)
    return config


def parse_uuid(raw: str) -> uuid.UUID | None:
    try:
        return uuid.UUID(raw)
    except ValueError:
        return None


def prepare_cache(keyid, args):
    # A directory is created for all cached data, the baseurl is sanitized from all slashes
    # to make sure no path traversal is possible
    h = hashlib.sha256()
    h.update(keyid.encode("utf-8"))
    sanitized_host = h.hexdigest()
    if args.cache:
        path = args.cache + "/" + sanitized_host
    else:
        path = os.environ['OMD_ROOT'] + "/tmp/patchmon/" + sanitized_host
    tmpdir = Path(path)
    tmpdir.mkdir(parents=True, exist_ok=True)
    return path


def gently_exit(error_msg, conf):
    if conf['monitoring_plugin'] == True:
        output = f"ERROR | \n{error_msg}"
        print(output)
        exit(3)
    agentstats = { "error": error_msg }
    print('<<<patchmon_server>>>')
    print(json.dumps(agentstats))
    exit(0)


def retrieve_hostlist(auth, url, conf):
    try:
        response = requests.get(url, auth=basic)
    except Exception as err:
        gently_exit(str(err), conf)
    if response.status_code > 200:
        gently_exit("Error retrieving host list. Got status code: " + str(response.status_code), conf)
    j = response.json()
    return j
    

def get_hostlist_from_fs(auth, url, maxage, path, conf):
    hostlist = path + "/hostlist.json"
    if os.path.exists(hostlist):
        if time.time() - os.path.getmtime(hostlist) < maxage:
            with open(hostlist, "r") as file:
                c = file.read()
                j = json.loads(c)
                return j
    j = retrieve_hostlist(auth, url, conf)
    with open(hostlist, "w") as file:
        file.write(json.dumps(j))
    return j


def get_hostlist_from_storage(auth, url, maxage, storage, conf):
    jstr = storage.read("hostlist", None)
    if jstr:
        return json.loads(jstr)
    j = retrieve_hostlist(auth, url, conf)
    storage.unset(hostlist)
    storage.write("hostlist", json.dumps(j))
    return j


def get_hostlist(auth, url, maxage, storage, path, conf):
    if storage:
        return get_hostlist_from_storage(auth, url, maxage, storage, conf)
    else:
        return get_hostlist_from_fs(auth, url, maxage, path, conf)


def retrieve_hoststat(auth, url, conf):
    error = 'Error retrieving host statistics. Since this happened after retrieving '\
        'the host list, this is most likely caused by an outdated version of PatchMon. '
    try:
        response = requests.get(url, auth=basic)
    except Exception as err:
        gently_exit(error + str(err), conf)
    if response.status_code > 200:
        gently_exit(error + "Got status code: " + str(response.status_code), conf)
    j = response.json()
    return j


def retrieve_hostextra(auth, extraurl, conf):
    error = 'Error retrieving host details. Since this happened after retrieving '\
        'the host list, this is most likely caused by an outdated version of PatchMon. '
    try:
        response = requests.get(extraurl, auth=basic)
    except Exception as err:
        gently_exit(error + str(err), conf)
    if response.status_code > 200:
        gently_exit(error + "Got status code: " + str(response.status_code), conf)
    j = response.json()
    return j


def retrieve_pkglist(auth, pkglisturl, oldpackages, conf):
    error = 'Error retrieving package list. Since this happened after retrieving '\
        'the host list, this is most likely caused by an outdated version of PatchMon. '
    try:
        response = requests.get(pkglisturl, auth=basic, params={"updates_only": "true"})
    except Exception as err:
        gently_exit(error + str(err), conf)
    if response.status_code > 200:
        gently_exit(error + "Got status code: " + str(response.status_code), conf)
    j = response.json()["packages"]
    plist = compare_pkglist(j, oldpackages)
    return plist


def compare_pkglist(packages, oldpackages):
    t_now = time.time()
    plist = {}
    for p in packages:
        if p["name"] in oldpackages:
            pmeta = oldpackages[p["name"]]
            if oldpackages[p["name"]]["is_security_update"] is True:
                pmeta["is_security_update"] = True
        else:
            pmeta = { 
                "is_security_update": p["is_security_update"],
                "first_seen" : t_now,
            }
        plist[p["name"]] = pmeta
    return plist
        
    
def get_all_hostsmeta_from_fs(hostlist, maxage, path):
    stats = {
        "oldhosts": [],
        "missinghosts": [],
        "hostdata": {},
        "hostsskipped": 0,
    }
    for h in hostlist['hosts']:
        hostid = h['id']
        # Validating the UUID makes sure, no crafted id field can be used to
        # read and write in the site file system
        if parse_uuid(hostid):
            hostjson = path + "/" + hostid + ".json"
            if os.path.exists(hostjson):
                fileage = time.time() - os.path.getmtime(hostjson)
                with open(hostjson, "r") as file:
                    c = file.read()
                    j = json.loads(c)
                    j['fileage'] = fileage
                    j['maxage'] = maxage
                    stats['hostdata'][hostid] = j
                if fileage > maxage:
                    stats['oldhosts'].append(hostid)
            else:
                stats['missinghosts'].append(hostid)
    return stats


def get_all_hostsmeta_from_storage(hostlist, maxage, storage):
    stats = {
        "oldhosts": [],
        "missinghosts": [],
        "hostdata": {},
        "hostsskipped": 0,
    }
    for h in hostlist['hosts']:
        hostid = h['id']
        if parse_uuid(hostid):
            # storage.unset(hostid)
            jsdata = storage.read(hostid, None)
            if jsdata:
                j = json.loads(jsdata)
                fileage = time.time() - j['timestamp']
                j['fileage'] = fileage
                j['maxage'] = maxage
                stats['hostdata'][hostid] = j
                if fileage > maxage:
                    stats['oldhosts'].append(hostid)
            else:
                stats['missinghosts'].append(hostid)
    return stats


def narrow_down_hostlist(hostlist, fullhostlist, args):
    resultlist = hostlist
    if args.single_host:
        resultlist = []
        for host in fullhostlist["hosts"]:
            if host["id"] in hostlist:
                if args.name == "id" and host["id"] == args.single_host:
                    return [ host["id"] ]
                elif args.name == "hostname" and host["hostname"] == args.single_host:
                    return [ host["id"] ]
                elif host["friendly_name"] == args.single_host:
                    return [ host["id"] ]
    return resultlist


def get_all_hoststats(auth, urls, hostlist, maxage, maxexec, storage, path, args, conf):
    url = urls["stats"]
    xurl = urls["extra"]
    if storage:
        stats = get_all_hostsmeta_from_storage(hostlist, maxage, storage)
    else:
        stats = get_all_hostsmeta_from_fs(hostlist, maxage, path)
    tstart = time.time()
    retrievehostlist = stats['missinghosts'] + stats['oldhosts']
    retrievehostlist = narrow_down_hostlist(retrievehostlist, hostlist, args)
    for hostid in retrievehostlist:
        if time.time() - tstart < maxexec:
            statsurl = url.format(baseurl=args.baseurl, uuid=hostid)
            extraurl = xurl.format(baseurl=args.baseurl, uuid=hostid)
            j = retrieve_hoststat(auth, statsurl, conf)
            # Retrieving extra data like reboot required needs another API call
            if args.reboot:
                x = retrieve_hostextra(auth, extraurl, conf)
                j['needs_reboot'] = 1 if x['needs_reboot'] else 0
                j['reboot_reason'] = str(x['reboot_reason'])
            if args.grace and j['outdated_packages'] > 0:
                pkglisturl = urls["pkglist"].format(baseurl=args.baseurl, uuid=hostid)
                oldpackages = {}
                if hostid in stats['hostdata'] and "packages" in stats['hostdata'][hostid]:
                    oldpackages = stats['hostdata'][hostid]["packages"]
                x = retrieve_pkglist(auth, pkglisturl, oldpackages, conf)
                j["packages"] = x
            else:
                j["packages"] = {}
            j['timestamp'] = time.time()
            if storage:
                storage.unset(hostid)
                storage.write(hostid, json.dumps(j))
            else:
                hostjson = path + "/" + hostid + ".json"
                with open(hostjson, "w") as file:
                    file.write(json.dumps(j))
            j['fileage'] = 0.0
            j['maxage'] = maxage
            stats['hostdata'][hostid] = j
        else:
            stats['hostsskipped'] += 1
    return stats


def get_access_token(args):
    userpass = None
    try:
        # The 2.5 method first: Checkmk cares for differentiating between plain password and store reference
        userpass = resolve_secret_option(args, "secret").reveal().split(":")
        return userpass
    except:
        # We have Checkmk 2.4 or 2.3 where the password store is an internal API
        # Here we have to differentiate between the two possible parameters
        if args.secret_id:
            store_reference = args.secret_id.split(":")[0]
            try:
                userpass = legacy_pw_store.lookup(legacy_pw_store.password_store_path(), store_reference).split(":")
                return userpass
            except:
                # Either the lookup failed (Checkmk 2.3 and explicit password) or the legacy_pw_store is not available.
                # In such cases, assume that a plain password was passed
                userpass = args.secret_id.split(":")[0]
                return userpass
        else:
            userpass = args.secret.split(":")
            return userpass

def get_hostid(hostlist, args):
    for host in hostlist['hosts']:
        if args.name == "id" and host["id"] == args.single_host:
            return host["id"]
        elif args.name == "hostname" and host["hostname"] == args.single_host:
            return host["id"]
        elif host["friendly_name"] == args.single_host:
            return host["id"]


def generate_monitoring_plugins_output(hostlist, allstats, args, t_start, conf):
    hostid = get_hostid(hostlist, args)
    if hostid is None:
        t_end = time.time()
        duration = t_end - t_start
        output = f"query failed | duration={duration:.3f}s;;;;\nThe host you specified with the CLI option --single-host does not seem to exist. If it's a fresh host, you have to wait until the cached host list has been invalidated."
        print(output)
        exit(3)
    host_data = allstats['hostdata'][hostid]
    if args.only_reboot:
        generate_monitoring_plugins_output_reboot(host_data, t_start, conf)
    else:
        generate_monitoring_plugins_output_patches(host_data, t_start, conf)
    

def generate_monitoring_plugins_output_reboot(host_data, t_start, conf):
    t_end = time.time()
    duration = t_end - t_start
    if not 'needs_reboot' in host_data:
        output = f"query failed | duration={duration:.3f}s;;;;\nThe needs_reboot flag in the cached data is missing. This is most likely due to two checks (one for patches and one for reboots being run on a single host. Add the CLI flag --reboot also to the check for patches to query and cache the needs_reboot flog."
        print(output)
        exit(3)
    if host_data['needs_reboot'] > 0:
        reboot_reason = host_data['reboot_reason'].replace('|', '')
        output = f"reboot required | duration={duration:.3f}s;;;;\nReason given: {reboot_reason}"
        print(output)
        exit(conf['states'][2])
    else:
        output = f"no reboot required | duration={duration:.3f}s;;;;"
        print(output)
        exit(0)


def generate_monitoring_plugins_output_patches(host_data, t_start, conf):
    t_end = time.time()
    duration = t_end - t_start
    if host_data['security_updates'] > 0:
        output = f"security updates missing | security_updates={host_data['security_updates']};;;; total_updates={host_data['outdated_packages']};;;; duration={duration:.3f}s;;;;\n{host_data['security_updates']} security updates are missing, in total {host_data['outdated_packages']} updates are missing."
        print(output)
        exit(conf['states'][0])
    elif host_data['outdated_packages'] > 0:
        output = f"updates missing | security_updates={host_data['security_updates']};;;; total_updates={host_data['outdated_packages']};;;; duration={duration:.3f}s;;;;\n{host_data['outdated_packages']} updates are missing, none of those are security updates."
        print(output)
        exit(conf['states'][1])
    else:
        output = f"no updates missing | security_updates={host_data['security_updates']};;;; total_updates={host_data['outdated_packages']};;;; duration={duration:.3f}s;;;;"
        print(output)
        exit(0)


def generate_checkmk_output(hostlist, allstats, args, t_start):
    t_end = time.time()
    for h in hostlist['hosts']:
        print('<<<<' + h[args.name] + '>>>>')
        print('<<<patchmon_patches>>>')
        try:
            allstats['hostdata'][h['id']]['url'] = urls["host"].format(baseurl=args.baseurl.rstrip('/'), uuid=h['id'])
            print(json.dumps(allstats['hostdata'][h['id']]))
            print('<<<labels:sep(0)>>>')
            print('{"patchmon/monitored":"true"}')
        except KeyError:
            print('{ "error": "No data" }')
        print('<<<<>>>>')

    t_end = time.time()
    agentstats = {
        "hoststotal": len(hostlist['hosts']),
        "hostsskipped": allstats["hostsskipped"],
        "duration": t_end - t_start
    }
    print('<<<patchmon_server>>>')
    print(json.dumps(agentstats))


def check_monitoring_plugins_parameters(config, t_start):
    t_end = time.time()
    duration = t_end - t_start
    if config['baseurl'] is None:
        output = f"query failed | duration={duration:.3f}s;;;;\nSpecify the base URL for your patchmon server including the protocol ('http://' or 'https://'), but without the trailing slash with the CLI option --baseurl."
        print(output)
        exit(3)
    if (config['secret'] is None and config['secret_id'] is None):
        output = f"query failed | duration={duration:.3f}s;;;;\nSpecify colon separated user:pass pair with the CLI option --secret."
        print(output)
        exit(3)
    if config['cache'] is None:
        output = f"query failed | duration={duration:.3f}s;;;;\nSpecify a cache directory to store the host list and the patch states with the CLI option --cache."
        print(output)
        exit(3)
    if config['single_host'] is None:
        output = f"query failed | duration={duration:.3f}s;;;;\nSpecify the host for which to query for updates with the CLI option --single-host."
        print(output)
        exit(3)
urls = {
    "api": "{baseurl}/api/v1/api/hosts",
    "host": "{baseurl}/hosts/{uuid}",
    "hosts": None,
    "stats": "{baseurl}/api/v1/api/hosts/{uuid}/stats",
    "extra": "{baseurl}/api/v1/api/hosts/{uuid}/system",
    "pkglist": "{baseurl}/api/v1/api/hosts/{uuid}/packages"
}

t_start = time.time()
args = get_cli_arguments()
conf = create_config(args)

if args.monitoring_plugin:
    check_monitoring_plugins_parameters(conf, t_start)  

urls["hosts"] = urls["api"].format(baseurl=args.baseurl)
userpass = get_access_token(args)
basic = requests.auth.HTTPBasicAuth(userpass[0], userpass[1])


# The user identifier is randomly generated and thus should be globally unique.
# Since PatchMon host groups might be associated with this identifier, using it
# as identifier for the Storage means we do not need to pass a hostname. It also
# Prevents problems from using the same baseurl (potentially with different host
# groups).
#
# Since the same problem occurs for the hacky caching, use this key instead of
# baseurl from now on.

try:
    stor = Storage('patchmon', userpass[0])
    tmp_path = None
except NameError:
    stor = None
    tmp_path = prepare_cache(userpass[0], args)

# First retrieve the host list
hostlist = get_hostlist(basic, urls["hosts"], conf['listage'], stor, tmp_path, conf)

# Now retrieve info for all hosts
allstats = get_all_hoststats(basic, urls, hostlist, conf['hostage'], conf['maxexec'], stor, tmp_path, args, conf)

if args.monitoring_plugin:
    generate_monitoring_plugins_output(hostlist, allstats, args, t_start, conf)
else:
    generate_checkmk_output(hostlist, allstats, args, t_start)
